#!/bin/sh

#                                  _
#    _____  ____ _ _ __ ___  _ __ | | ___
#   / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
#  |  __/>  < (_| | | | | | | |_) | |  __/
#   \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
#                           |_|

while getopts u: name
do
    case $name in
        u) uri=$OPTARG ;;
    esac
done

option=$(printf 'chromium\nlynx\n' | dmenu -p "Open $uri with:")

case "$option" in
    chromium) chromium "$uri" &       ;;
    lynx)     xterm -e lynx "$uri" &  ;;
esac
