#!/bin/bash

current_uri=$1
text_entered=$2

case "$text_entered" in
    goo\ *)
        echo "go_uri https://www.google.com/search?&q=${text_entered#* }"
        ;;
    wi\ *)
        echo "go_uri_new https://en.wikipedia.org/wiki/${text_entered#* }"
        ;;
    lynx)
        xterm -e lynx "$current_uri" &
        echo nop
        ;;
    *)
        echo "go_uri $text_entered"
        ;;
esac
