#!/bin/sh

#                                  _
#    _____  ____ _ _ __ ___  _ __ | | ___
#   / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
#  |  __/>  < (_| | | | | | | |_) | |  __/
#   \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
#                           |_|
#
# This script is an example. It allows for some basic browsing. It does
# not implement anything magical, though.
#
# You -- the user -- are encouraged to customize this script or write
# your own one.

while getopts c:h:k:t:u: name
do
    case $name in
        c) context=$OPTARG ;;
        h) hover_uri=$OPTARG ;;
        k) key=$OPTARG ;;
        t) context_specific_text=$OPTARG ;;
        u) current_uri=$OPTARG ;;
    esac
done

case "$context" in
    inputbox)
        case "$context_specific_text" in
            ddg\ *)
                echo "go_uri https://duckduckgo.com/?q=${context_specific_text#* }"
                ;;
            *)
                echo "go_uri $context_specific_text"
                ;;
        esac
        ;;
    handle_context_menu_uri)
        # Do something with the URI in $context_specific_text. There is
        # nothing meaningful that can be done by default.
        true
        ;;
    hid_button)
        case "$key" in
            2)  [ -n "$hover_uri" ] && echo go_uri_new_tab "$hover_uri" ;;
            8)  echo  go_backward           ;;
            9)  echo  go_forward            ;;
        esac
        ;;
    hid_key)
        case "$key" in
            Escape)  echo  abort_load              ;;
            M-3)     echo  search_backward         ;;
            M-c)     echo  reload_user_certs       ;;
            M-d)     echo  download_manager_open   ;;
            M-D)     echo  download_manager_close  ;;
            M-e)     echo  new_tab                 ;;
            M-k)     echo  search_initiate         ;;
            M-l)     echo  focus_input_box         ;;
            M-n)     echo  search_forward          ;;
            M-q)     echo  quit                    ;;
            M-r)     echo  reload                  ;;
            M-w)     echo  go_home                 ;;
        esac
        ;;
    hid_scroll)
        case "$key" in
            C-y)      echo  zoom_increase  ;;
            C-Y)      echo  zoom_decrease  ;;
            C-x|C-X)  echo  zoom_reset     ;;
        esac
        ;;
esac
