#!/bin/sh

#                                  _
#    _____  ____ _ _ __ ___  _ __ | | ___
#   / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
#  |  __/>  < (_| | | | | | | |_) | |  __/
#   \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
#                           |_|

text=$1
text_key=${text%% *}
text_value=${text#* }

db=${XDG_CONFIG_HOME:-~/.config}/lariza/keywordsearch

urlencode()
{
    printf '%s' "$1" | od -t x1 -An | tr ' ' '%' | tr -d '\n'
}

if test -r "$db"
then
    while read db_key db_pattern
    do
        if [ "$db_key" = "$text_key" ]
        then
            printf "go_uri $db_pattern\n" "$(urlencode "$text_value")"
            exit 0
        fi
    done <"$db"
fi

echo go_uri "$text"
